# Generated by Django 2.1.3 on 2018-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('government', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('charge', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('licenceNum', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('charge', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('licenceNum', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('charge', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repairshop',
            fields=[
                ('repairshop', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('licenceNum', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('charge', models.CharField(max_length=20)),
            ],
        ),
    ]
